/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu Jun 27 20:14:09 2019. */

#ifndef PB_BLUETOOTH_PB_H_INCLUDED
#define PB_BLUETOOTH_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _BTProvide {
    char fsmState[24];
    float robotX;
    float robotY;
    bool onLine;
    bool switchOk;
    float goalLength;
    float ballStrength;
    float ballAngle;
/* @@protoc_insertion_point(struct:BTProvide) */
} BTProvide;

/* Default values for struct fields */

/* Initializer values for message structs */
#define BTProvide_init_default                   {"", 0, 0, 0, 0, 0, 0, 0}
#define BTProvide_init_zero                      {"", 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BTProvide_fsmState_tag                   1
#define BTProvide_robotX_tag                     2
#define BTProvide_robotY_tag                     3
#define BTProvide_onLine_tag                     4
#define BTProvide_switchOk_tag                   5
#define BTProvide_goalLength_tag                 6
#define BTProvide_ballStrength_tag               7
#define BTProvide_ballAngle_tag                  8

/* Struct field encoding specification for nanopb */
extern const pb_field_t BTProvide_fields[9];

/* Maximum encoded size of messages (where known) */
#define BTProvide_size                           55

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BLUETOOTH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
