#ifndef CONFIG_H
#define CONFIG_H

#define LS_NUM 48
#define LS_CALIBRATION_COUNT 10
#define LINE_AVOID_SPEED 80
#define LS_CALIBRATION_BUFFER 300 //A: 40, B, 300

#define NO_LINE_ANGLE 400
#define NO_LINE_SIZE 3

#define LINE_CORNER_ANGLE_THRESHOLD 30
#define LINE_ANGLE_BUFFER -10
#define LINE_ANGLE_BUFFER_CORNER -10
#define LS_MOVEMENT_SMALL_MULTIPLIER 0.5

#define OVER_LINE_SPEED 220
#define LINE_SPEED 255
#define LINE_SPEED_MULTIPLIER 0.7
#define LINE_TRACK_SPEED 100

#define LINE_SMALL_SIZE 0
#define LINE_BIG_SIZE 1.5

#endif CONFIG_H
